# Generated by Django 4.2.7 on 2023-11-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
        migrations.CreateModel(
            name='ShiftDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('employee', models.ManyToManyField(to='staff.employee')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.shift')),
            ],
        ),
    ]
