# Generated by Django 4.2.7 on 2023-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_shift_date_remove_shift_employee_shiftday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftday',
            name='employee',
            field=models.ManyToManyField(related_name='employees', to='staff.employee'),
        ),
    ]
