# Generated by Django 4.2.7 on 2023-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_shiftday_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='id',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
