# Generated by Django 4.2.7 on 2023-11-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_shiftday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='shiftday',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='StandartShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.shift')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.statusemployee')),
            ],
        ),
    ]
