# Generated by Django 4.2.7 on 2023-11-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_statusemployee_remove_shiftday_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
