# Generated by Django 4.2.7 on 2023-11-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_employee_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='id',
            new_name='number',
        ),
    ]
