# Generated by Django 4.2.7 on 2023-11-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_rename_id_shift_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusemployee',
            name='name',
        ),
        migrations.AddField(
            model_name='statusemployee',
            name='choice',
            field=models.CharField(choices=[('ED', 'Education'), ('SI', 'Sick'), ('VA', 'Vacation'), ('DO', 'Day off'), ('TO', 'Time off'), ('OJ', 'On the job'), ('AB', 'Absenteeism')], default='OJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='shiftday',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.shift'),
        ),
        migrations.AlterField(
            model_name='standartshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employee'),
        ),
        migrations.AlterField(
            model_name='standartshift',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.shift'),
        ),
        migrations.AlterField(
            model_name='standartshift',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_emp', to='staff.statusemployee'),
        ),
    ]
