# Generated by Django 4.2.7 on 2023-11-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_remove_statusemployee_name_statusemployee_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='number',
            new_name='id',
        ),
    ]
