# Generated by Django 4.2.7 on 2023-11-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_rename_number_shift_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusemployee',
            name='choice',
            field=models.CharField(choices=[('ED', 'Education'), ('SI', 'Sick'), ('VA', 'Vacation'), ('DO', 'Day off'), ('TO', 'Time off'), ('OJ', 'On the job'), ('AB', 'Absenteeism')], default='OJ', max_length=2, unique=True),
        ),
    ]
